title: Guide to Data Transformations
description: A definitve guide to all kinds of data transformations
theme: jekyll-theme-tactile
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - title.md
  - article1.md
  - article2.md
  - article3.md
  #- index.md
  #- README.md
  #- CONTRIBUTING.md
  #- LICENSE.md
  #- COPYING.md
  #- CODE_OF_CONDUCT.md
  #- CONTRIBUTING.md
  #- ISSUE_TEMPLATE.md
  #- PULL_REQUEST_TEMPLATE.md